connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.catalog-name=default
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://airflow-db:5432/${ENV:ICEBERG_CATALOG_DB}
iceberg.jdbc-catalog.connection-user=${ENV:POSTGRES_USER}
iceberg.jdbc-catalog.connection-password=${ENV:POSTGRES_PASSWORD}
iceberg.jdbc-catalog.default-warehouse-dir=s3://warehouse/

fs.native-s3.enabled=true
s3.region=us-east-1
s3.endpoint=http://minio:9000
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
s3.path-style-access=true
